[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
path = "src/1.rs"
name = "1"
#[[bin]]
#path = "src/2.rs"
#name = "2"
